runners:
  - name: "azure-runner"
    cloud: "azure"
    instance_type: "Standard_D4s_v3"
    machine_image: "canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:latest"
    preemptible: false
    labels:
      - "cirun-azure-runner"

  - name: "azure-windows-runner"
    cloud: "azure"
    instance_type: "Standard_D4s_v3"
    machine_image: "microsoftwindowsdesktop:windows-11:win11-24h2-pro:latest"
    labels:
      - "cirun-azure-windows-runner"