package tech.loveace.testhook;

enum MockPart {
    SEMESTER,
    ACADEMIC,
    EXAM_INDEX,
    SCHOOL_EXAMS,
    OTHER_EXAMS,
    SCORES_INDEX,
    SCORES_DATA,
    SCHEDULE_INDEX,
    STUDENT_SCHEDULE,
    COURSE_CATALOG_INDEX,
    COURSE_CATALOG_DATA,
    CAMPUS_CARD_SESSION,
    CAMPUS_CARD_BALANCE,
    CAMPUS_CARD_TRANSACTIONS,
    TRAINING_PLAN_SUMMARY,
    TRAINING_PLAN_DETAIL,
}
